#pragma once

typedef enum {
  ESP_SUCCESS = 0,
  ESP_ERR_INVALID_PORT = -1,
  ESP_ERR_PORT_OPEN = -2,
  ESP_ERR_PORT_CONFIG = -3,
  ESP_ERR_RESET_FAILED = -4,
  ESP_ERR_READ_FAILED = -5,
  ESP_ERR_WRITE_FAILED = -6,
  ESP_ERR_TIMEOUT = -7,
  ESP_ERR_INVALID_RESPONSE = -8,
  ESP_ERR_INVALID_ARG = -9,
  ESP_ERR_UNKNOWN,
} esp_error_t;